function Squares({ className }) {
  return (
    <div className={className}>
      <svg
        width="212"
        height="212"
        viewBox="0 0 212 212"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="32" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="64" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="96" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="128" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="160" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect x="192" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect y="32" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="32"
          width="20"
          height="20"
          rx="10"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="32"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="32"
          width="20"
          height="20"
          rx="10"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="32"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="32"
          width="20"
          height="20"
          rx="10"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="32"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect y="64" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="64"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect y="96" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="96"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="96"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="96"
          width="20"
          height="20"
          rx="10"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="96"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="96"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="96"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect y="128" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="128"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect y="160" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="160"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="160"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="160"
          width="20"
          height="20"
          rx="10"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="160"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="160"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="160"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect y="192" width="20" height="20" fill="white" fill-opacity="0.2" />
        <rect
          x="32"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="64"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="96"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="128"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="160"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
        <rect
          x="192"
          y="192"
          width="20"
          height="20"
          fill="white"
          fill-opacity="0.2"
        />
      </svg>
    </div>
  );
}

export default Squares;
